define("AutoGeneratedPageUserTaskElementViewModelResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		SelectFromLookupTypeCaption: "Select from lookup",
		DropDownListTypeCaption: "Drop down list",
		DateAndTimeFormatCaption: "Date and time",
		DateFormatCaption: "Date",
		TimeFormatCaption: "Time",
		ItemFloderLabelCaption: "Item folder",
		NotesLabelCaption: "Notes"
	};
	var localizableImages = {

	};
	return {
		localizableStrings: localizableStrings,
		localizableImages: localizableImages
	};
});