define("AutoGeneratedPageUserTaskPropertiesPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		RecommendationLabelCaption: "To whom should the page be shown?",
		RecommendationCaption: "Recommendation to user",
		OwnerIdCaption: "Owner",
		InformationOnStepCaption: "User hints",
		TitleCaption: "Page title",
		ButtonsCaption: "Buttons",
		ItemsCaption: "Page Items",
		EntitySchemaContainerUIdCaption: "Which record to connect the page to?",
		EntityIdCaption: "Record of connected object",
		NotesMenuItemCaption: "Notes",
		ItemFolderMenuItemCaption: "Item block",
		TextMenuItemCaption: "Text field",
		SelectionMenuItemCaption: "Selection field",
		BooleanMenuItemCaption: "Boolean",
		DateTimeMenuItemCaption: "Date\/time",
		IntegerMenuItemCaption: "Integer",
		DecimalMenuItemCaption: "Decimal",
		MoveUpMenuItemCaption: "Move up",
		MoveDownMenuItemCaption: "Move down",
		EntitySchemaUIdCaption: "Connected object",
		ProcessInformationText: "Displays a custom page that is automatically generated based on the process element properties. You can specify which custom fields and buttons a custom page will contain. Perfect for creating custom step-by-step Wizards and forms. \u003Ca href=\u0022#\u0022 data-context-help-code=\u0022AutoGeneratedPageUserTaskPropertiesPage\u0022 \u003ERead more...\u003C\/a\u003E"
	};
	var localizableImages = {
		BlackToolsButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "BlackToolsButtonImage",
				hash: "1e35a244fbf576117229fbd866db69ac",
				resourceItemExtension: ".png"
			}
		},
		FieldsGroupTypeImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "FieldsGroupTypeImage",
				hash: "9b17d05932b29d0a8b7830fec7b79263",
				resourceItemExtension: ".svg"
			}
		},
		CommentTypeImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "CommentTypeImage",
				hash: "42a0790b77a51d8b66fddc69f260554b",
				resourceItemExtension: ".svg"
			}
		},
		CloseButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "CloseButtonImage",
				hash: "c5d6edb4bb180f8b30301d3dca7a12d8",
				resourceItemExtension: ".svg"
			}
		},
		ToolsButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "ToolsButtonImage",
				hash: "67b9187f776eb0c57c20bd86b63d4efc",
				resourceItemExtension: ".svg"
			}
		},
		InfoButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "InfoButtonImage",
				hash: "f67a1328d14dbc7091cc94589d7d2148",
				resourceItemExtension: ".svg"
			}
		},
		AddButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "AddButtonImage",
				hash: "7bc1980b519205382d39ea022bd498f8",
				resourceItemExtension: ".svg"
			}
		},
		AddParameterButton: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "AddParameterButton",
				hash: "a74df1a7d753e6067ab248949eb47d97",
				resourceItemExtension: ".png"
			}
		},
		ParameterEditToolsButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "ParameterEditToolsButtonImage",
				hash: "df03c3177a972b7f3b6987430f988ca3",
				resourceItemExtension: ".svg"
			}
		}
	};
	return {
		localizableStrings: localizableStrings,
		localizableImages: localizableImages
	};
});