define("AutoGeneratedPageV2UtilitiesResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		UnsupportedType: "Type is not supported"
	};
	var localizableImages = {

	};
	return {
		localizableStrings: localizableStrings,
		localizableImages: localizableImages
	};
});