define("AutoGeneratedPageUserTaskPropertiesPageResources", ["terrasoft"], function(Terrasoft) {
	var localizableStrings = {
		RecommendationLabelCaption: "\u041A\u043E\u043C\u0443 \u043E\u0442\u043E\u0431\u0440\u0430\u0437\u0438\u0442\u044C \u0441\u0442\u0440\u0430\u043D\u0438\u0446\u0443?",
		RecommendationCaption: "\u0420\u0435\u043A\u043E\u043C\u0435\u043D\u0434\u0430\u0446\u0438\u044F \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044E",
		OwnerIdCaption: "\u041E\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0435\u043D\u043D\u044B\u0439",
		InformationOnStepCaption: "\u041F\u043E\u0434\u0441\u043A\u0430\u0437\u043A\u0430 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044E",
		TitleCaption: "\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u0441\u0442\u0440\u0430\u043D\u0438\u0446\u044B",
		ButtonsCaption: "\u041A\u043D\u043E\u043F\u043A\u0438",
		ItemsCaption: "\u042D\u043B\u0435\u043C\u0435\u043D\u0442\u044B \u0441\u0442\u0440\u0430\u043D\u0438\u0446\u044B",
		EntitySchemaContainerUIdCaption: "\u041A \u043A\u0430\u043A\u043E\u0439 \u0437\u0430\u043F\u0438\u0441\u0438 \u043F\u0440\u0438\u0432\u044F\u0437\u0430\u0442\u044C \u0441\u0442\u0440\u0430\u043D\u0438\u0446\u0443?",
		EntityIdCaption: "\u0417\u0430\u043F\u0438\u0441\u044C \u043E\u0431\u044A\u0435\u043A\u0442\u0430 \u043F\u0440\u0438\u0432\u044F\u0437\u043A\u0438",
		NotesMenuItemCaption: "\u041A\u043E\u043C\u043C\u0435\u043D\u0442\u0430\u0440\u0438\u0439",
		ItemFolderMenuItemCaption: "\u0413\u0440\u0443\u043F\u043F\u0430 \u043F\u043E\u043B\u0435\u0439",
		TextMenuItemCaption: "\u0421\u0442\u0440\u043E\u043A\u043E\u0432\u043E\u0435 \u043F\u043E\u043B\u0435",
		SelectionMenuItemCaption: "\u0421\u043F\u0440\u0430\u0432\u043E\u0447\u043D\u0438\u043A",
		BooleanMenuItemCaption: "\u041B\u043E\u0433\u0438\u0447\u0435\u0441\u043A\u043E\u0435",
		DateTimeMenuItemCaption: "\u0414\u0430\u0442\u0430\/\u0432\u0440\u0435\u043C\u044F",
		IntegerMenuItemCaption: "\u0426\u0435\u043B\u043E\u0435 \u0447\u0438\u0441\u043B\u043E",
		DecimalMenuItemCaption: "\u0414\u0440\u043E\u0431\u043D\u043E\u0435 \u0447\u0438\u0441\u043B\u043E",
		MoveUpMenuItemCaption: "\u041F\u0435\u0440\u0435\u043C\u0435\u0441\u0442\u0438\u0442\u044C \u0432\u0432\u0435\u0440\u0445",
		MoveDownMenuItemCaption: "\u041F\u0435\u0440\u0435\u043C\u0435\u0441\u0442\u0438\u0442\u044C \u0432\u043D\u0438\u0437",
		EntitySchemaUIdCaption: "\u041E\u0431\u044A\u0435\u043A\u0442 \u043F\u0440\u0438\u0432\u044F\u0437\u043A\u0438",
		ProcessInformationText: "\u041E\u0442\u043E\u0431\u0440\u0430\u0436\u0430\u0435\u0442 \u0441\u0442\u0440\u0430\u043D\u0438\u0446\u0443, \u043A\u043E\u0442\u043E\u0440\u0430\u044F \u0431\u044B\u043B\u0430 \u0430\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u0435\u0441\u043A\u0438 \u0441\u0433\u0435\u043D\u0435\u0440\u0438\u0440\u043E\u0432\u0430\u043D\u0430 \u0441\u043E\u0433\u043B\u0430\u0441\u043D\u043E \u043F\u0430\u0440\u0430\u043C\u0435\u0442\u0440\u0430\u043C \u044D\u043B\u0435\u043C\u0435\u043D\u0442\u0430. \u041F\u0440\u0438 \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0435 \u0432\u044B \u043C\u043E\u0436\u0435\u0442\u0435 \u0443\u043A\u0430\u0437\u0430\u0442\u044C, \u043A\u0430\u043A\u0438\u0435 \u043A\u043D\u043E\u043F\u043A\u0438 \u0438 \u043F\u043E\u043B\u044F \u0434\u043E\u043B\u0436\u043D\u044B \u0431\u044B\u0442\u044C \u043D\u0430 \u0441\u0442\u0440\u0430\u043D\u0438\u0446\u0435. \n\n\u0414\u0430\u043D\u043D\u044B\u0439 \u044D\u043B\u0435\u043C\u0435\u043D\u0442 \u043E\u0442\u043B\u0438\u0447\u043D\u043E \u043F\u043E\u0434\u0445\u043E\u0434\u0438\u0442 \u0434\u043B\u044F \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u044F \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C\u0441\u043A\u0438\u0445 \u043C\u0430\u0441\u0442\u0435\u0440\u043E\u0432 \u0438 \u0444\u043E\u0440\u043C \u0430\u043D\u043A\u0435\u0442. \u003Ca href=\u0022#\u0022 data-context-help-code=\u0022AutoGeneratedPageUserTaskPropertiesPage\u0022\u003E\u041F\u0435\u0440\u0435\u0439\u0442\u0438...\u003C\/a\u003E"
	};
	var localizableImages = {
		BlackToolsButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "BlackToolsButtonImage",
				hash: "1e35a244fbf576117229fbd866db69ac",
				resourceItemExtension: ".png"
			}
		},
		FieldsGroupTypeImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "FieldsGroupTypeImage",
				hash: "9b17d05932b29d0a8b7830fec7b79263",
				resourceItemExtension: ".svg"
			}
		},
		CommentTypeImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "CommentTypeImage",
				hash: "42a0790b77a51d8b66fddc69f260554b",
				resourceItemExtension: ".svg"
			}
		},
		CloseButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "CloseButtonImage",
				hash: "c5d6edb4bb180f8b30301d3dca7a12d8",
				resourceItemExtension: ".svg"
			}
		},
		ToolsButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "ToolsButtonImage",
				hash: "67b9187f776eb0c57c20bd86b63d4efc",
				resourceItemExtension: ".svg"
			}
		},
		InfoButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "InfoButtonImage",
				hash: "f67a1328d14dbc7091cc94589d7d2148",
				resourceItemExtension: ".svg"
			}
		},
		AddButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "AddButtonImage",
				hash: "7bc1980b519205382d39ea022bd498f8",
				resourceItemExtension: ".svg"
			}
		},
		AddParameterButton: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "AddParameterButton",
				hash: "a74df1a7d753e6067ab248949eb47d97",
				resourceItemExtension: ".png"
			}
		},
		ParameterEditToolsButtonImage: {
			source: 3,
			params: {
				schemaName: "AutoGeneratedPageUserTaskPropertiesPage",
				resourceItemName: "ParameterEditToolsButtonImage",
				hash: "df03c3177a972b7f3b6987430f988ca3",
				resourceItemExtension: ".svg"
			}
		}
	};
	return {
		localizableStrings: localizableStrings,
		localizableImages: localizableImages
	};
});